title: "Jesse Jenks"
description: "Homepage for Jesse Jenks"

author:
  name: 'Jesse Jenks'
  first_name: 'Jesse'
  last_name: 'Jenks'
  email: 'JesseEndoJenks@pugetsound.edu'
  github_username: 'jessejenks'

markdown: kramdown

permalink: /blog/:title