title: "Jesse Jenks"
description: "Homepage for Jesse Endo Jenks"

author:
  name: "Jesse Jenks"
  first_name: "Jesse"
  last_name: "Jenks"
  email: "JesseEndoJenks@gmail.com"
  github_username: "jessejenks"

markdown: kramdown

collections:
  posts:
    permalink: /blog/:title
  writings:
    output: true
    permalink: /blog/writings/:title